### ISSUE TITLE
Register in WPML an escaped version of dropdown option

### ISSUE THREAD

**Issue by dikiyforester** [AppThemes/WPML-Bridge#10]
Since https://github.com/AppThemes/ClassiPress/pull/368 we have to register escaped data in WPML. Otherwise drop-down options won't be translated correctly.

This changes probably needs check the CP version, and upgrade procedure will probably need.

**Comment by meloniq** [comment]
PR: https://github.com/AppThemes/WPML-Bridge/pull/11
